---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange
  name: exchange
  namespace: bank-services
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exchange
---
