#update-yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-yaml
spec:
  params:  
  - name: yaml-path
  - name: appImage
  - name: buildRevision  
  workspaces:
  - name: source
  steps:
  - name: update-deploymwnt-image
    image: registry.access.redhat.com/ubi8/ubi:8.0
    workingDir: "$(workspaces.source.path)/$(params.yaml-path)"
    script: |
      #!/bin/sh
      echo "updating $(params.yaml-path) image to $(params.appImage):$(params.buildRevision)"
      sed -i "s#$(params.appImage):[a-zA-Z0-9]\\+#$(params.appImage):$(params.buildRevision)#" deployment.yaml
