---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: interest-rate
  name: interest-rate
  namespace: bank-services
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: exchange
---
