---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interest-rate
  name: interest-rate
  namespace: bank-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interest-rate
  template:
    metadata:
      labels:
        app: interest-rate
    spec:
      containers:
        - image: quay.io/amr_fahmy/dev-interest-rate-service:v05
          name: interest-rate
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: DATABASE_PASSWORD
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SVC
              value: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
---

